import apiClient from './client';

export const adminApi = {
  getDashboard: () => apiClient.get('/admin/dashboard'),
  getUsers: (params?: any) => apiClient.get('/admin/users', { params }),
  createUser: (data: any) => apiClient.post('/admin/users', data),
  updateUser: (id: string, data: any) => apiClient.put(`/admin/users/${id}`, data),
  updateUserStatus: (id: string, is_active: boolean) => apiClient.put(`/admin/users/${id}/status`, { is_active }),
  deleteUser: (id: string) => apiClient.delete(`/admin/users/${id}`),
  getClinics: (params?: any) => apiClient.get('/admin/clinics', { params }),
  createClinic: (data: any) => apiClient.post('/admin/clinics', data),
  updateClinic: (id: string, data: any) => apiClient.put(`/admin/clinics/${id}`, data),
  updateClinicStatus: (id: string, is_active: boolean) => apiClient.put(`/admin/clinics/${id}/status`, { is_active }),
  deleteClinic: (id: string) => apiClient.delete(`/admin/clinics/${id}`),
  getPendingReviews: (params?: any) => apiClient.get('/admin/reviews/pending', { params }),
  approveReview: (id: string) => apiClient.put(`/admin/reviews/${id}/approve`),
  rejectReview: (id: string) => apiClient.delete(`/admin/reviews/${id}`),
  getPlans: () => apiClient.get('/admin/plans'),
  createPlan: (data: any) => apiClient.post('/admin/plans', data),
  updatePlan: (id: string, data: any) => apiClient.put(`/admin/plans/${id}`, data),
  deletePlan: (id: string) => apiClient.delete(`/admin/plans/${id}`),
  getSubscriptions: (params?: any) => apiClient.get('/admin/subscriptions', { params }),
  assignSubscription: (data: any) => apiClient.post('/admin/subscriptions', data),
  updateSubscription: (id: string, data: any) => apiClient.put(`/admin/subscriptions/${id}`, data),
  cancelSubscription: (id: string) => apiClient.delete(`/admin/subscriptions/${id}`),
  getAuditLogs: (params?: any) => apiClient.get('/admin/audit-logs', { params }),
};
